import '../../features/presets/domain/entities/preset.dart';

final List<Preset> builtInPresets = [
  Preset(
    id: 'delta_deep_sleep',
    name: 'Deep Sleep',
    description: 'Delta waves (2 Hz) for deep, restorative sleep',
    leftFrequency: 100.0,
    rightFrequency: 102.0,
    category: PresetCategory.sleep,
    defaultDuration: const Duration(minutes: 60),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'delta_healing',
    name: 'Healing Rest',
    description: 'Delta waves (1 Hz) for physical healing and recovery',
    leftFrequency: 150.0,
    rightFrequency: 151.0,
    category: PresetCategory.sleep,
    defaultDuration: const Duration(minutes: 45),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'theta_meditation',
    name: 'Deep Meditation',
    description: 'Theta waves (6 Hz) for deep meditative states',
    leftFrequency: 200.0,
    rightFrequency: 206.0,
    category: PresetCategory.meditation,
    defaultDuration: const Duration(minutes: 30),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'theta_creativity',
    name: 'Creative Flow',
    description: 'Theta waves (5 Hz) for creativity and insight',
    leftFrequency: 180.0,
    rightFrequency: 185.0,
    category: PresetCategory.meditation,
    defaultDuration: const Duration(minutes: 25),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'alpha_relaxation',
    name: 'Calm Relaxation',
    description: 'Alpha waves (10 Hz) for relaxation and stress relief',
    leftFrequency: 200.0,
    rightFrequency: 210.0,
    category: PresetCategory.relaxation,
    defaultDuration: const Duration(minutes: 20),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'alpha_light_focus',
    name: 'Light Focus',
    description: 'Alpha waves (12 Hz) for calm, focused attention',
    leftFrequency: 220.0,
    rightFrequency: 232.0,
    category: PresetCategory.relaxation,
    defaultDuration: const Duration(minutes: 30),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'beta_focus',
    name: 'Laser Focus',
    description: 'Beta waves (18 Hz) for concentration and productivity',
    leftFrequency: 300.0,
    rightFrequency: 318.0,
    category: PresetCategory.focus,
    defaultDuration: const Duration(minutes: 45),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'beta_study',
    name: 'Study Mode',
    description: 'Beta waves (15 Hz) for learning and memorization',
    leftFrequency: 250.0,
    rightFrequency: 265.0,
    category: PresetCategory.focus,
    defaultDuration: const Duration(minutes: 50),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'gamma_peak',
    name: 'Peak Awareness',
    description: 'Gamma waves (40 Hz) for heightened perception',
    leftFrequency: 400.0,
    rightFrequency: 440.0,
    category: PresetCategory.energy,
    defaultDuration: const Duration(minutes: 15),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
  Preset(
    id: 'gamma_insight',
    name: 'Cognitive Boost',
    description: 'Gamma waves (32 Hz) for enhanced cognition',
    leftFrequency: 350.0,
    rightFrequency: 382.0,
    category: PresetCategory.energy,
    defaultDuration: const Duration(minutes: 20),
    isBuiltIn: true,
    createdAt: DateTime(2024, 1, 1),
  ),
];
